# Video paths to transcribe (required)
video_path: "/home/rteam2/m15kh/auto-subtitle/data/time.mp4"
# subtitle_path: "/home/rteam2/m15kh/auto-subtitle/subtitled/time/subtitle/time.json" #if None, it will be saved in the same directory as the video
subtitle_path: null
output_dir: "subtitled"
debug_mode: True


process_subtitle:
# Whisper model options
  model: "large"  # Choices: tiny, base, small, medium, large
  # Output options
  verbose: false
  # Language processing
  task: "transcribe"  # Choices: transcribe, translate
  language: "en"  # Source language (auto for automatic detection)
  translate_to: null



video_editor:


