#-----------------------------------MAIN-----------------------------------
# video_path: "/home/rteam2/m15kh/auto-subtitle/output/youtube/21_youtube_Motivate_me/download/Cristiano_Ronaldo_Winning_Mentality__Cristiano_Ronaldo_Motivation.mp4"
video_path: "https://youtube.com/shorts/kJ23zVr3HkE?si=M1O4CTvycVwbnZwR"

# subtitle_path: "/home/rteam2/m15kh/auto-subtitle/output/youtube/21_youtube_Motivate_me/subtitle/Cristiano_Ronaldo_Winning_Mentality__Cristiano_Ronaldo_Motivation.json" # if you want to use subtitle file, set the path
subtitle_path: null
output_dir: "output"
debug_mode: True
GPT_API: "AIzaSyD7"
#-----------------------------------youtube-----------------------------------
youtube:
  quality: "best"  # Options: "best", "worst", or format code like "137+140"
  resolution: "1080p"  # Options: "240p", "360p", "480p", "720p", "1080p", etc. 
                        # Note: For Shorts, resolution is automatically determined for best compatibility
  download_full: True  # Set to true to download the full video, false to use segments
  video_type: "regular"  # Options: "short" or "regular" - manually specify video type

  # Filename format configuration
  filename_format:
    use_counter: True    # Include a sequential number in filenames
    use_channel: True    # Include channel name in filenames 
    prefix: ""           # Optional prefix before the counter

  segments:
    - time:
        start: "00:23:01"  # Format: HH:MM:SS
        end: "00:23:30"
      aspect_ratio:
        mode: "scale"  # Using the new scale mode (adds black bars for regular videos)
        ratio: "9:16"  # Common values: "16:9" (landscape), "9:16" (portrait/shorts)

  output:
    filename: null            # Set to null to use auto-generated filenames with counter and channel
    merge: true               # Whether to merge all segments into single video

#-----------------------------------subtitle-----------------------------------
process_subtitle:
    enabled: true
  # Whisper model options
    model: "large"  # Choices: tiny, base, small, medium, large
    # Output options
    verbose: false
    # Language processing
    task: "translate"  # Choices: transcribe, translate
    language: "en"  # Source language (auto for automatic detection)
    translate_to: 'fa_IR'   #'fa_IR'  #null for no translation


#-----------------------------------video_editor-----------------------------------
video_editor:

  logo:
    enabled: false  # Set to false to disable logo
    output_video_path: /home/rteam2/m15kh/auto-subtitle/notebook/add-logo/add-logoooo.mp4
  
  subtitle:
    enabled: true  # Set to false to disable subtitle
    text: "@Max_o_Ava"
    fontsize: 30
    color: "red"
    background_color: "rgba(0,0,0,0.4)"
    # movement line removed as it's now randomly selected in the script
    shadow:
      enabled: true
      color: "black"
      offset_x: 2
      offset_y: 2
      blur: 3
    effect: "pulse"  # Options: none, fade_in_out, pulse, bounce
    animation_speed: 1.0  # Speed multiplier for effects


